// The product's interactive face - generated by the AI OS UI Synthesizer.
// Vanilla JS; imports the synthesized brain. No framework, no per-user image gen.
import { runCapability } from "./capability.mjs";
import { renderCard } from "./card.mjs";

const CONFIG = {
  "questions": [
    "What's a word that describes your energy when you're at your best?",
    "What's a book or song that feels like it was made for you?",
    "What's a strength you've always had but never got to use?",
    "What's a small moment that makes you feel completely at ease?",
    "What's a value you'd never compromise on?",
    "What's a word that captures how you want to be remembered?",
    "What's a place where you feel most like yourself?",
    "What's a phrase you'd use to describe your ideal day?"
  ],
  "askName": true,
  "hasCard": true,
  "capture": {
    "enabled": true,
    "unlocks": "the full result"
  },
  "resultFields": [
    "archetype_name",
    "one_line_essence",
    "visual_metaphor",
    "strengths",
    "shadow_traits",
    "motto / chapter theme-word",
    "narrative"
  ],
  "productName": "Alter Ego",
  "intro": "FREE, forever. Paste nothing — just answer ~8 quick, revealing questions. In"
};
const RENDER_CARD = renderCard;

const $ = (t, attrs, kids) => {
  const el = document.createElement(t);
  for (const k in (attrs || {})) {
    if (k === "style") Object.assign(el.style, attrs[k]);
    else if (k === "class") el.className = attrs[k];
    else if (k === "html") el.innerHTML = attrs[k];
    else el.setAttribute(k, attrs[k]);
  }
  for (const c of (kids || [])) el.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
  return el;
};
const sp = (n) => "var(--aios-space-" + n + ", " + (n * 0.25) + "rem)";

function fieldLabel(name) { return String(name).replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()); }

function root() { return document.getElementById("aios-app-root"); }
function clear() { const r = root(); if (r) r.innerHTML = ""; return r; }

// ---- questionnaire screen ----
function renderQuestions() {
  const r = clear(); if (!r) return;
  r.setAttribute("data-screen", "questions");
  const form = $("form", { "data-aios-form": "1", style: { display: "flex", flexDirection: "column", gap: sp(4), maxWidth: "40rem", margin: "0 auto" } });
  if (CONFIG.intro) form.appendChild($("p", { style: { fontSize: "var(--aios-text-lg, 1.125rem)", opacity: "0.9" } }, [CONFIG.intro]));
  const inputs = [];
  if (CONFIG.askName) {
    const wrap = $("label", { style: { display: "flex", flexDirection: "column", gap: sp(1) } }, ["Your name (optional)"]);
    const inp = $("input", { type: "text", name: "aios-name", "data-aios-name": "1", autocomplete: "given-name", style: { padding: sp(3), fontSize: "1rem", border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)", boxSizing: "border-box", width: "100%", maxWidth: "100%" } });
    wrap.appendChild(inp); form.appendChild(wrap); form._name = inp;
  }
  CONFIG.questions.forEach((q, i) => {
    const wrap = $("label", { style: { display: "flex", flexDirection: "column", gap: sp(1) } }, [(i + 1) + ". " + q]);
    const inp = $("input", { type: "text", name: "aios-q" + i, "data-aios-q": String(i), required: "true", style: { padding: sp(3), fontSize: "1rem", border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)", boxSizing: "border-box", width: "100%", maxWidth: "100%" } });
    wrap.appendChild(inp); form.appendChild(wrap); inputs.push(inp);
  });
  const btn = $("button", { type: "submit", "data-aios-submit": "1", style: { padding: sp(3) + " " + sp(4), fontSize: "1rem", border: "0", borderRadius: "var(--aios-radius-md,6px)", background: "var(--aios-color-accent,#2563eb)", color: "var(--aios-color-on-accent,#fff)", cursor: "pointer" } }, ["See my result"]);
  form.appendChild(btn);
  form.addEventListener("submit", async (e) => {
    e.preventDefault();
    const answers = inputs.map((x) => (x.value || "").trim());
    if (answers.some((a) => !a)) { return; }
    const firstName = form._name ? (form._name.value || "").trim() : "";
    btn.disabled = true; btn.textContent = "Reading...";
    try {
      const reading = await runCapability({ answers: answers, firstName: firstName, businessName: firstName });
      renderResult(reading, { answers, firstName });
    } catch (err) {
      const r2 = root(); if (r2) r2.appendChild($("p", { style: { color: "var(--aios-color-warning,#b45309)" } }, ["Something went wrong generating your result."]));
      btn.disabled = false; btn.textContent = "See my result";
    }
  });
  r.appendChild(form);
}

// ---- result screen (teaser card) + capture ----
function renderResult(reading, ctx) {
  const r = clear(); if (!r) return;
  r.setAttribute("data-screen", "result");
  const box = $("div", { "data-aios-result": "1", style: { maxWidth: "40rem", margin: "0 auto", display: "flex", flexDirection: "column", gap: sp(4) } });

  // The templated CSS/HTML card (no per-user image generation).
  if (CONFIG.hasCard && RENDER_CARD) {
    try {
      const card = RENDER_CARD(reading, 0);
      // A synthesized renderCard may return either a raw HTML string OR an object
      // { html, css }. Handle both so the templated card actually renders.
      let html = "", css = "";
      if (typeof card === "string") html = card;
      else if (card && typeof card === "object") { html = card.html || card.markup || ""; css = card.css || ""; }
      if (html || css) {
        if (css) box.appendChild($("style", { html: String(css) }));
        box.appendChild($("div", { "data-aios-card": "1", style: { maxWidth: "100%", overflowX: "auto" }, html: String(html) }));
      }
    } catch (e) { /* fall through to fields */ }
  }
  if (!box.querySelector("[data-aios-card]")) {
    // No card (e.g. a diagnostic): render the declared result fields as the teaser.
    box.appendChild(renderFields(reading, CONFIG.resultFields.slice(0, 3), "teaser"));
  }

  if (CONFIG.capture.enabled) {
    box.appendChild(renderCapture(reading, ctx));
  } else {
    box.appendChild(renderFields(reading, CONFIG.resultFields, "full"));
    box.setAttribute("data-aios-full", "1");
  }
  r.appendChild(box);
}

function renderFields(reading, fields, tag) {
  const wrap = $("div", { "data-aios-fields": tag, style: { display: "flex", flexDirection: "column", gap: sp(3) } });
  for (const f of fields) {
    const v = reading[f];
    if (v == null || v === "") continue;
    const val = Array.isArray(v) ? v.join(" \u00b7 ") : String(v);
    wrap.appendChild($("div", null, [ $("strong", null, [fieldLabel(f) + ": "]), val ]));
  }
  return wrap;
}

// ---- capture: write to CRM BEFORE revealing the full reading ----
function renderCapture(reading, ctx) {
  const wrap = $("div", { "data-aios-capture": "1", style: { display: "flex", flexDirection: "column", gap: sp(2), padding: sp(4), border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)" } });
  wrap.appendChild($("p", null, ["Enter your email to unlock " + (CONFIG.capture.unlocks || "your full result") + "."]));
  const email = $("input", { type: "email", "data-aios-email": "1", placeholder: "you@example.com", required: "true", style: { padding: sp(3), fontSize: "1rem", border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)", boxSizing: "border-box", width: "100%", maxWidth: "100%" } });
  const btn = $("button", { type: "button", "data-aios-capture-submit": "1", style: { padding: sp(3), border: "0", borderRadius: "var(--aios-radius-md,6px)", background: "var(--aios-color-accent,#2563eb)", color: "var(--aios-color-on-accent,#fff)", cursor: "pointer" } }, ["Unlock my full result"]);
  const note = $("p", { "aria-live": "polite", style: { minHeight: "1.2em", fontSize: "0.9rem", opacity: "0.8" } });
  btn.addEventListener("click", async () => {
    const addr = (email.value || "").trim();
    if (!/.+@.+\..+/.test(addr)) { note.textContent = "Please enter a valid email."; return; }
    btn.disabled = true; note.textContent = "Saving...";
    const archetype = reading.archetype_name || reading.overall_grade || reading.archetype || "result";
    const tags = deriveTags(reading, ctx);
    try {
      const res = await fetch("/capture", { method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ email: addr, first_name: (ctx && ctx.firstName) || "", archetype: archetype, tags: tags }) });
      if (!res.ok) throw new Error("capture failed");
      // Only AFTER the capture is recorded do we reveal the full reading.
      const box = wrap.parentNode;
      wrap.remove();
      box.appendChild(renderFields(reading, CONFIG.resultFields, "full"));
      box.setAttribute("data-aios-full", "1");
    } catch (e) { btn.disabled = false; note.textContent = "Could not save right now - try again."; }
  });
  wrap.appendChild(email); wrap.appendChild(btn); wrap.appendChild(note);
  return wrap;
}

function deriveTags(reading, ctx) {
  const tags = [];
  const arch = reading.archetype_name || reading.overall_grade || reading.archetype;
  if (arch) tags.push(String(arch).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""));
  // answer-derived: a couple distinctive words from the user's answers
  const words = ((ctx && ctx.answers) || []).join(" ").toLowerCase().match(/[a-z]{5,}/g) || [];
  for (const w of [...new Set(words)].slice(0, 3)) tags.push(w);
  return tags;
}

function injectResponsiveReset() {
  const style = document.createElement("style");
  // Mobile-clean by construction: nothing exceeds the viewport, no horizontal
  // scroll, and reduced-motion is honored (we add no animations, but declare it).
  style.textContent = "html,body{margin:0;max-width:100%;overflow-x:hidden}" +
    "#aios-app-root{box-sizing:border-box;max-width:100%;padding:var(--aios-space-4,1rem)}" +
    "#aios-app-root *{max-width:100%;box-sizing:border-box}" +
    "#aios-app-root img{height:auto}" +
    "@media (prefers-reduced-motion: reduce){*{animation:none!important;transition:none!important}}";
  document.head.appendChild(style);
}

function start() {
  const r = root();
  if (!r) return;
  injectResponsiveReset();
  renderQuestions();
}
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
else start();
