// The product's interactive face - generated by the AI OS UI Synthesizer.
// Vanilla JS; imports the synthesized brain. No framework, no per-user image gen.
import { runCapability } from "./capability.mjs";
import { renderCard } from "./card.mjs";

const CONFIG = {
  "questions": [
    "What's the one word that describes how you show up in a group?",
    "What kind of problem do you love solving most?",
    "When you feel most like yourself, what are you doing?",
    "What quality do you admire in others that you also have?",
    "What's the most authentic part of you that you share?"
  ],
  "askName": true,
  "hasCard": true,
  "capture": {
    "enabled": true,
    "unlocks": "the full result"
  },
  "resultFields": [
    "archetype_name",
    "one_line_essence",
    "visual_metaphor",
    "strengths",
    "shadow_traits",
    "motto / chapter theme-word",
    "narrative"
  ],
  "productName": "Alter Ego",
  "intro": "Free, forever. Answer 5 quick, revealing questions and meet your Alter Ego.",
  "share": {
    "url": "https://macleanmarket.com/alterego",
    "cta": "What's your Alter Ego?"
  },
  "marketLink": {
    "label": "More from MacLean Market",
    "url": "https://macleanmarket.com"
  },
  "rewardCards": [
    {
      "id": "friend_group_ego",
      "label": "Friend Group Ego",
      "kind": "card",
      "lens": "friend_group"
    },
    {
      "id": "shadow_ego",
      "label": "Shadow Ego",
      "kind": "card",
      "lens": "shadow"
    }
  ],
  "bioLine": {
    "enabled": true,
    "linkedin": true
  }
};
const RENDER_CARD = renderCard;

const $ = (t, attrs, kids) => {
  const el = document.createElement(t);
  for (const k in (attrs || {})) {
    if (k === "style") Object.assign(el.style, attrs[k]);
    else if (k === "class") el.className = attrs[k];
    else if (k === "html") el.innerHTML = attrs[k];
    else el.setAttribute(k, attrs[k]);
  }
  for (const c of (kids || [])) el.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
  return el;
};
const sp = (n) => "var(--aios-space-" + n + ", " + (n * 0.25) + "rem)";

function fieldLabel(name) { return String(name).replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()); }

function root() { return document.getElementById("aios-app-root"); }
function clear() { const r = root(); if (r) r.innerHTML = ""; return r; }

// ---- questionnaire screen ----
function renderQuestions() {
  const r = clear(); if (!r) return;
  r.setAttribute("data-screen", "questions");
  const form = $("form", { "data-aios-form": "1", style: { display: "flex", flexDirection: "column", gap: sp(4), maxWidth: "40rem", margin: "0 auto" } });
  if (CONFIG.intro) form.appendChild($("p", { style: { fontSize: "var(--aios-text-lg, 1.125rem)", opacity: "0.9" } }, [CONFIG.intro]));
  const inputs = [];
  if (CONFIG.askName) {
    const wrap = $("label", { style: { display: "flex", flexDirection: "column", gap: sp(1) } }, ["Your name (optional)"]);
    const inp = $("input", { type: "text", name: "aios-name", "data-aios-name": "1", autocomplete: "given-name", style: { padding: sp(3), fontSize: "1rem", border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)", boxSizing: "border-box", width: "100%", maxWidth: "100%" } });
    wrap.appendChild(inp); form.appendChild(wrap); form._name = inp;
  }
  CONFIG.questions.forEach((q, i) => {
    const wrap = $("label", { style: { display: "flex", flexDirection: "column", gap: sp(1) } }, [(i + 1) + ". " + q]);
    const inp = $("input", { type: "text", name: "aios-q" + i, "data-aios-q": String(i), required: "true", style: { padding: sp(3), fontSize: "1rem", border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)", boxSizing: "border-box", width: "100%", maxWidth: "100%" } });
    wrap.appendChild(inp); form.appendChild(wrap); inputs.push(inp);
  });
  const btn = $("button", { type: "submit", "data-aios-submit": "1", style: { padding: sp(3) + " " + sp(4), fontSize: "1rem", border: "0", borderRadius: "var(--aios-radius-md,6px)", background: "var(--aios-color-accent,#2563eb)", color: "var(--aios-color-on-accent,#fff)", cursor: "pointer" } }, ["See my result"]);
  form.appendChild(btn);
  form.addEventListener("submit", async (e) => {
    e.preventDefault();
    const answers = inputs.map((x) => (x.value || "").trim());
    if (answers.some((a) => !a)) { return; }
    const firstName = form._name ? (form._name.value || "").trim() : "";
    btn.disabled = true; btn.textContent = "Reading...";
    try {
      const reading = await runCapability({ answers: answers, firstName: firstName, businessName: firstName });
      renderResult(reading, { answers, firstName });
    } catch (err) {
      const r2 = root(); if (r2) r2.appendChild($("p", { style: { color: "var(--aios-color-warning,#b45309)" } }, ["Something went wrong generating your result."]));
      btn.disabled = false; btn.textContent = "See my result";
    }
  });
  r.appendChild(form);
}

// ---- deterministic templated card (the factory's guaranteed, $0 share-worthy
// card, built from the reading DATA). Used whenever the synthesized renderCard is
// absent or returns something invalid (e.g. bare CSS with no markup). Horizontal:
// it reads CONFIG.resultFields + the reading object, carries no venture strings.
function esc(s) {
  return String(s).replace(/[&<>"']/g, function (c) {
    return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c];
  });
}
var TC_GRADS = [
  "linear-gradient(135deg,#6a11cb,#2575fc)", "linear-gradient(135deg,#8e2de2,#4a00e0)",
  "linear-gradient(135deg,#0f2027,#2c5364)", "linear-gradient(135deg,#11998e,#38ef7d)",
  "linear-gradient(135deg,#c31432,#240b36)", "linear-gradient(135deg,#f7971e,#c1440e)",
  "linear-gradient(135deg,#1a2980,#26d0ce)", "linear-gradient(135deg,#ee0979,#ff6a00)"
];
function tcGrad(seed) {
  var s = 0, str = String(seed || "");
  for (var i = 0; i < str.length; i++) s = (s + str.charCodeAt(i)) % 9973;
  return TC_GRADS[s % TC_GRADS.length];
}
var TEMPLATED_CARD_CSS =
  ".aios-tc{position:relative;max-width:34rem;margin:0 auto;padding:2rem 1.75rem;border-radius:18px;color:#fff;" +
  "font-family:inherit;box-shadow:0 18px 44px -14px rgba(0,0,0,.5);overflow:hidden}" +
  ".aios-tc::before{content:'';position:absolute;inset:0;background:radial-gradient(130% 80% at 100% 0,rgba(255,255,255,.20),transparent 60%);pointer-events:none}" +
  ".aios-tc>*{position:relative}" +
  ".aios-tc-kicker{text-transform:uppercase;letter-spacing:.18em;font-size:.7rem;opacity:.82;margin:0 0 .55rem}" +
  ".aios-tc-headline{font-size:2rem;line-height:1.1;font-weight:800;margin:0 0 .4rem;text-shadow:0 2px 14px rgba(0,0,0,.28)}" +
  ".aios-tc-sub{font-size:1.1rem;font-style:italic;opacity:.95;margin:0 0 1.3rem;line-height:1.4}" +
  ".aios-tc-sec{margin:0 0 1rem}" +
  ".aios-tc-label{text-transform:uppercase;letter-spacing:.12em;font-size:.64rem;opacity:.72;margin:0 0 .3rem}" +
  ".aios-tc-val{font-size:1rem;line-height:1.5;margin:0;white-space:pre-wrap}" +
  ".aios-tc-chips{display:flex;flex-wrap:wrap;gap:.4rem;margin:.15rem 0 0;padding:0;list-style:none}" +
  ".aios-tc-chip{background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.30);border-radius:999px;padding:.28rem .72rem;font-size:.85rem}" +
  ".aios-tc-foot{margin:1.4rem 0 0;padding-top:1rem;border-top:1px solid rgba(255,255,255,.22);font-size:.7rem;letter-spacing:.14em;text-transform:uppercase;opacity:.78}";
function tcSection(label, value) {
  if (value == null || value === "") return "";
  if (Array.isArray(value)) {
    var items = value.filter(function (v) { return v != null && v !== ""; });
    if (!items.length) return "";
    var chips = items.map(function (v) { return '<li class="aios-tc-chip">' + esc(String(v)) + "</li>"; }).join("");
    return '<div class="aios-tc-sec"><p class="aios-tc-label">' + esc(label) + '</p><ul class="aios-tc-chips">' + chips + "</ul></div>";
  }
  return '<div class="aios-tc-sec"><p class="aios-tc-label">' + esc(label) + '</p><p class="aios-tc-val">' + esc(String(value)) + "</p></div>";
}
// fieldsOpt overrides the field ORDER (reward cards carry their own fields, not
// the main result_fields); kicker overrides the small top label (e.g. "Shadow Ego").
function renderTemplatedCard(reading, fieldsOpt, kicker) {
  reading = reading || {};
  var fields = (fieldsOpt && fieldsOpt.length) ? fieldsOpt.slice()
    : (CONFIG.resultFields && CONFIG.resultFields.length) ? CONFIG.resultFields.slice()
    : Object.keys(reading);
  fields = fields.filter(function (f) {
    var v = reading[f]; return v != null && v !== "" && !(Array.isArray(v) && !v.length);
  });
  var headField = fields[0];
  var headline = headField ? reading[headField] : (CONFIG.productName || "Your result");
  if (Array.isArray(headline)) headline = headline.join(", ");
  var rest = fields.slice(1);
  var subField = null;
  for (var i = 0; i < rest.length; i++) {
    var v = reading[rest[i]];
    if (typeof v === "string" && v.length > 0 && v.length <= 140) { subField = rest[i]; break; }
  }
  var secHtml = "";
  for (var j = 0; j < rest.length; j++) {
    if (rest[j] === subField) continue;
    secHtml += tcSection(fieldLabel(rest[j]), reading[rest[j]]);
  }
  var kick = kicker || CONFIG.productName;
  var grad = tcGrad((kicker ? kicker + "|" : "") + headline);
  var html =
    '<article class="aios-tc" data-aios-templated-card="1" style="background:' + grad + '">' +
    (kick ? '<p class="aios-tc-kicker">' + esc(kick) + "</p>" : "") +
    '<h2 class="aios-tc-headline">' + esc(String(headline)) + "</h2>" +
    (subField ? '<p class="aios-tc-sub">' + esc(String(reading[subField])) + "</p>" : "") +
    secHtml +
    '<p class="aios-tc-foot">your result \u00b7 keep or share</p>' +
    "</article>";
  return { html: html, css: TEMPLATED_CARD_CSS };
}

// ---- Wave-2: share (the growth loop), polished reveal, market link ----
function pickFields(reading) {
  const f = (CONFIG.resultFields && CONFIG.resultFields.length) ? CONFIG.resultFields.slice() : Object.keys(reading || {});
  return f.filter((k) => { const v = reading[k]; return v != null && v !== "" && !(Array.isArray(v) && !v.length); });
}
function cardHeadline(reading) {
  const f = pickFields(reading); const v = reading[f[0]];
  return Array.isArray(v) ? v.join(", ") : (v == null ? "" : String(v));
}
function cardEssence(reading) {
  const f = pickFields(reading);
  for (let i = 1; i < f.length; i++) { const v = reading[f[i]]; if (typeof v === "string" && v.length > 0 && v.length <= 160) return v; }
  return "";
}
// Pre-filled share text: the archetype + one-line essence + the market link, so
// the user taps post and never writes the caption.
function shareCaption(reading, title) {
  const head = title || cardHeadline(reading);
  const ess = cardEssence(reading);
  const text = ess ? (head + " \u2014 " + ess) : head;
  const url = CONFIG.share && CONFIG.share.url ? CONFIG.share.url : "";
  return url ? (text + "\n\n" + url) : text;
}
async function doShare(caption) {
  try { if (navigator.share) { await navigator.share({ text: caption }); return "shared"; } }
  catch (e) { if (e && e.name === "AbortError") return "cancelled"; }
  try { await navigator.clipboard.writeText(caption); return "copied"; }
  catch (e) { return "failed"; }
}
// The HERO share control that travels with a card. small=true is the reward
// cards' slightly smaller (still prominent) control.
function renderShareBar(reading, title, small) {
  const wrap = $("div", { "data-aios-share": "1", style: { display: "flex", flexDirection: "column", alignItems: "center", gap: sp(1) } });
  const btn = $("button", { type: "button", "data-aios-share-btn": "1", class: "aios-share-cta" + (small ? " sm" : "") }, [
    "\u21ea " + ((CONFIG.share && CONFIG.share.cta) || "Share your card"),
  ]);
  const note = $("p", { "aria-live": "polite", style: { minHeight: "1em", fontSize: "0.78rem", opacity: "0.7", textAlign: "center", margin: "0", whiteSpace: "pre-wrap" } });
  btn.addEventListener("click", async () => {
    const cap = shareCaption(reading, title);
    const r = await doShare(cap);
    note.textContent = r === "copied" ? "Caption copied - paste it anywhere."
      : r === "shared" ? "Thanks for sharing!"
      : r === "cancelled" ? ""
      : cap; // last resort: show the caption to copy manually
  });
  wrap.appendChild(btn); wrap.appendChild(note);
  return wrap;
}
// The polished, DESIGNED on-screen full reading (never the raw field dump).
function renderReading(reading, fields) {
  const wrap = $("div", { "data-aios-fields": "full", "data-aios-reading": "1", class: "aios-reading" });
  for (const f of fields) {
    const v = reading[f];
    if (v == null || v === "") continue;
    const sec = $("div", { class: "aios-reading-sec" });
    sec.appendChild($("p", { class: "aios-reading-label" }, [fieldLabel(f)]));
    if (Array.isArray(v)) {
      const ul = $("ul", { class: "aios-reading-chips" });
      for (const item of v) { if (item != null && item !== "") ul.appendChild($("li", { class: "aios-reading-chip" }, [String(item)])); }
      sec.appendChild(ul);
    } else {
      sec.appendChild($("p", { class: "aios-reading-val" }, [String(v)]));
    }
    wrap.appendChild(sec);
  }
  return wrap;
}
// The tertiary "More from MacLean Market ->" link (quiet footer-weight).
function renderMarketLink() {
  if (!CONFIG.marketLink || !CONFIG.marketLink.url) return null;
  const wrap = $("div", { class: "aios-market-wrap" });
  wrap.appendChild($("a", { class: "aios-market-link", href: CONFIG.marketLink.url, target: "_blank", rel: "noreferrer" }, [
    (CONFIG.marketLink.label || "More from MacLean Market") + " \u2192",
  ]));
  return wrap;
}
// A card (already-rendered element) + its prominent share control, as one unit.
function cardUnit(cardEl, reading, title, small) {
  const unit = $("div", { class: "aios-cardunit" });
  unit.appendChild(cardEl);
  if (CONFIG.hasCard) unit.appendChild(renderShareBar(reading, title, small));
  return unit;
}
// Build the main card element (synthesized-or-templated), or null.
function buildMainCard(reading) {
  if (!CONFIG.hasCard) return null;
  if (RENDER_CARD) {
    try {
      const card = RENDER_CARD(reading, 0);
      let html = "", css = "";
      if (typeof card === "string") html = card;
      else if (card && typeof card === "object") { html = card.html || card.markup || ""; css = card.css || ""; }
      if (/<[a-z][\s\S]*>/i.test(String(html))) {
        const holder = $("div", { style: { display: "contents" } });
        if (css) holder.appendChild($("style", { html: String(css) }));
        holder.appendChild($("div", { "data-aios-card": "1", "data-aios-card-source": "synthesized", style: { maxWidth: "100%", overflowX: "auto" }, html: String(html) }));
        return holder;
      }
    } catch (e) { /* fall through */ }
  }
  try { console.warn("[aios] synthesized card invalid or absent - rendered the deterministic templated card instead"); } catch (e2) {}
  const tc = renderTemplatedCard(reading);
  const holder = $("div", { style: { display: "contents" } });
  holder.appendChild($("style", { html: tc.css }));
  holder.appendChild($("div", { "data-aios-card": "1", "data-aios-card-source": "templated-fallback", style: { maxWidth: "100%", overflowX: "auto" }, html: tc.html }));
  return holder;
}

// ---- Wave-2: capture-reward cards (the value-for-email) ----
// The reward cards' DATA comes from the ENGINE (reading.reward_cards[id]) - the
// factory never fabricates a distinct reading client-side. If the engine did not
// produce a declared reward card, that is an HONEST GAP the runner/gate catches
// (the reward reveal fails), not something we paper over.
function rewardCardData(reading, rc) {
  const bag = reading && reading.reward_cards;
  if (bag && bag[rc.id] && typeof bag[rc.id] === "object") return bag[rc.id];
  if (reading && reading[rc.id] && typeof reading[rc.id] === "object") return reading[rc.id];
  return null;
}
function buildRewardCardEl(data, label) {
  const tc = renderTemplatedCard(data, Object.keys(data), label);
  const holder = $("div", { style: { display: "contents" } });
  holder.appendChild($("style", { html: tc.css }));
  holder.appendChild($("div", { "data-aios-card": "1", "data-aios-reward-card": "1", style: { maxWidth: "100%", overflowX: "auto" }, html: tc.html }));
  return holder;
}
// Render every declared reward card that the engine produced, each independently
// shareable, into the given container. Returns how many rendered.
function renderRewardCards(reading, into) {
  let n = 0;
  const mainHead = String(cardHeadline(reading) || "").trim().toLowerCase();
  for (const rc of (CONFIG.rewardCards || [])) {
    const data = rewardCardData(reading, rc);
    const sec = $("div", { "data-aios-reward": rc.id, style: { display: "flex", flexDirection: "column", gap: sp(2) } });
    sec.appendChild($("p", { class: "aios-reading-label", style: { margin: "0" } }, [rc.label || fieldLabel(rc.id)]));
    if (!data) {
      // Honest gap - never a fabricated card.
      sec.appendChild($("p", { style: { fontSize: "0.85rem", opacity: "0.65", margin: "0" } }, ["This bonus card was not produced for this build yet."]));
      sec.setAttribute("data-aios-reward-missing", "1");
    } else {
      const head = String(cardHeadline(data) || "").trim().toLowerCase();
      // Distinctness: a reward card that just restates the main card is a fail.
      if (head && head === mainHead) sec.setAttribute("data-aios-reward-redundant", "1");
      sec.appendChild(cardUnit(buildRewardCardEl(data, rc.label), data, cardHeadline(data), true));
      n++;
    }
    into.appendChild(sec);
  }
  return n;
}
// ---- Wave-2: the bio line (a copyable self-descriptor to append to a social bio) ----
// Data from the ENGINE (reading.bio_line: a string, or { universal, linkedin }).
// Defensive: strip emoji and hard-cap length so the on-screen line always meets
// the "no emoji, well under 150 chars" bar even if the engine drifts.
function sanitizeBio(s) {
  var t = String(s || "").replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\uFE0F]/gu, "").replace(/\s+/g, " ").trim();
  if (t.length > 150) t = t.slice(0, 147).replace(/\s+\S*$/, "") + "…";
  return t;
}
function bioLineData(reading) {
  var b = reading && reading.bio_line;
  if (!b) return null;
  if (typeof b === "string") return { universal: sanitizeBio(b) };
  if (typeof b === "object") return { universal: sanitizeBio(b.universal || b.line || ""), linkedin: b.linkedin ? sanitizeBio(b.linkedin) : "" };
  return null;
}
function copyRow(label, text) {
  var row = $("div", { "data-aios-bioline": "1", style: { display: "flex", flexDirection: "column", gap: sp(1) } });
  if (label) row.appendChild($("p", { class: "aios-reading-label", style: { margin: "0" } }, [label]));
  var line = $("p", { "data-aios-bio-text": "1", style: { margin: "0", fontSize: "1rem", lineHeight: "1.5" } }, [text]);
  var btn = $("button", { type: "button", "data-aios-copy": "1", class: "aios-copy-btn" }, ["Copy"]);
  var note = $("span", { "aria-live": "polite", style: { fontSize: "0.75rem", opacity: "0.7", marginLeft: sp(2) } });
  btn.addEventListener("click", async function () {
    try { await navigator.clipboard.writeText(text); note.textContent = "Copied!"; }
    catch (e) { note.textContent = "Select the line to copy."; }
  });
  var bar = $("div", { style: { display: "flex", alignItems: "center", gap: sp(2), flexWrap: "wrap" } });
  bar.appendChild(btn); bar.appendChild(note);
  row.appendChild(line); row.appendChild(bar);
  return row;
}
function renderBioLine(reading) {
  if (!CONFIG.bioLine || !CONFIG.bioLine.enabled) return null;
  var data = bioLineData(reading);
  var wrap = $("div", { "data-aios-bio": "1", class: "aios-reading", style: { gap: sp(3) } });
  wrap.appendChild($("p", { class: "aios-reading-label", style: { margin: "0" } }, ["Your bio line - add it to your profile"]));
  if (!data || !data.universal) {
    wrap.appendChild($("p", { style: { margin: "0", fontSize: "0.85rem", opacity: "0.65" } }, ["Your bio line was not produced for this build yet."]));
    wrap.setAttribute("data-aios-bio-missing", "1");
    return wrap;
  }
  wrap.appendChild(copyRow("", data.universal));
  if (CONFIG.bioLine.linkedin && data.linkedin) wrap.appendChild(copyRow("LinkedIn", data.linkedin));
  return wrap;
}

// The tease that earns the email: name the reward in enticing plain copy.
function captureTeaseText() {
  const labels = (CONFIG.rewardCards || []).map((rc) => rc.label || fieldLabel(rc.id)).filter(Boolean);
  const base = "Enter your email to get your full reading";
  if (!labels.length) return base + ".";
  const joined = labels.length === 1 ? labels[0]
    : labels.slice(0, -1).join(", ") + " and " + labels[labels.length - 1];
  return base + " plus your " + joined + ".";
}

// ---- result screen (teaser card) + capture ----
function renderResult(reading, ctx) {
  const r = clear(); if (!r) return;
  r.setAttribute("data-screen", "result");
  const box = $("div", { "data-aios-result": "1", style: { maxWidth: "40rem", margin: "0 auto", display: "flex", flexDirection: "column", gap: sp(4) } });

  // (1) HERO: the card + its prominent Share control travel together as one unit.
  const cardEl = buildMainCard(reading);
  if (cardEl) {
    box.appendChild(cardUnit(cardEl, reading, cardHeadline(reading), false));
  } else {
    // No card (e.g. a diagnostic): the result fields are the teaser.
    box.appendChild(renderFields(reading, CONFIG.resultFields.slice(0, 3), "teaser"));
  }

  // (2) SECOND: the email ask - or, when there is no capture, the full reveal now.
  if (CONFIG.capture.enabled) {
    box.appendChild(renderCapture(reading, ctx));
  } else {
    box.appendChild(renderReading(reading, pickFields(reading)));
    box.setAttribute("data-aios-full", "1");
  }

  // (3) TERTIARY: the quiet "More from MacLean Market" link (footer-weight).
  const ml = renderMarketLink();
  if (ml) box.appendChild(ml);

  r.appendChild(box);
}

function renderFields(reading, fields, tag) {
  const wrap = $("div", { "data-aios-fields": tag, style: { display: "flex", flexDirection: "column", gap: sp(3) } });
  for (const f of fields) {
    const v = reading[f];
    if (v == null || v === "") continue;
    const val = Array.isArray(v) ? v.join(" \u00b7 ") : String(v);
    wrap.appendChild($("div", null, [ $("strong", null, [fieldLabel(f) + ": "]), val ]));
  }
  return wrap;
}

// ---- capture: write to CRM BEFORE revealing the full reading ----
function renderCapture(reading, ctx) {
  const wrap = $("div", { "data-aios-capture": "1", style: { display: "flex", flexDirection: "column", gap: sp(2), padding: sp(4), border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)" } });
  // The TEASE: name the reward in enticing plain copy - the hook that earns the email.
  wrap.appendChild($("p", { class: "aios-tease", "data-aios-tease": "1" }, [captureTeaseText()]));
  const email = $("input", { type: "email", "data-aios-email": "1", placeholder: "you@example.com", required: "true", style: { padding: sp(3), fontSize: "1rem", border: "1px solid var(--aios-color-border,#ccc)", borderRadius: "var(--aios-radius-md,6px)", boxSizing: "border-box", width: "100%", maxWidth: "100%" } });
  const btn = $("button", { type: "button", "data-aios-capture-submit": "1", style: { padding: sp(3), border: "0", borderRadius: "var(--aios-radius-md,6px)", background: "var(--aios-color-accent,#2563eb)", color: "var(--aios-color-on-accent,#fff)", cursor: "pointer" } }, ["Unlock my full result"]);
  const note = $("p", { "aria-live": "polite", style: { minHeight: "1.2em", fontSize: "0.9rem", opacity: "0.8" } });
  btn.addEventListener("click", async () => {
    const addr = (email.value || "").trim();
    if (!/.+@.+\..+/.test(addr)) { note.textContent = "Please enter a valid email."; return; }
    btn.disabled = true; note.textContent = "Saving...";
    const archetype = reading.archetype_name || reading.overall_grade || reading.archetype || "result";
    const tags = deriveTags(reading, ctx);
    try {
      // Relative path (not "/capture"): resolves to /capture on the real server
      // (page served at /) AND to .../capture under a preview base path, so the
      // built app is walkable both live and in the at-the-gate preview.
      const res = await fetch("capture", { method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ email: addr, first_name: (ctx && ctx.firstName) || "", archetype: archetype, tags: tags }) });
      if (!res.ok) throw new Error("capture failed");
      // Only AFTER the capture is recorded do we reveal the full reading - as a
      // polished, DESIGNED section (never the raw field dump). The market link, if
      // present, stays last.
      const box = wrap.parentNode;
      wrap.remove();
      const mlEl = box.querySelector(".aios-market-wrap");
      const insert = (el) => { if (mlEl) box.insertBefore(el, mlEl); else box.appendChild(el); };
      // The full reading (polished), then the capture-reward cards (each shareable).
      insert(renderReading(reading, pickFields(reading)));
      if ((CONFIG.rewardCards || []).length) {
        const rewardWrap = $("div", { "data-aios-rewards": "1", style: { display: "flex", flexDirection: "column", gap: sp(4) } });
        renderRewardCards(reading, rewardWrap);
        insert(rewardWrap);
      }
      // The copyable bio line (a small self-descriptor for their social profile).
      const bio = renderBioLine(reading);
      if (bio) insert(bio);
      box.setAttribute("data-aios-full", "1");
    } catch (e) { btn.disabled = false; note.textContent = "Could not save right now - try again."; }
  });
  wrap.appendChild(email); wrap.appendChild(btn); wrap.appendChild(note);
  return wrap;
}

function deriveTags(reading, ctx) {
  const tags = [];
  const arch = reading.archetype_name || reading.overall_grade || reading.archetype;
  if (arch) tags.push(String(arch).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""));
  // answer-derived: a couple distinctive words from the user's answers
  const words = ((ctx && ctx.answers) || []).join(" ").toLowerCase().match(/[a-z]{5,}/g) || [];
  for (const w of [...new Set(words)].slice(0, 3)) tags.push(w);
  return tags;
}

function injectResponsiveReset() {
  const style = document.createElement("style");
  // Mobile-clean by construction: nothing exceeds the viewport, no horizontal
  // scroll, and reduced-motion is honored (we add no animations, but declare it).
  style.textContent = "html,body{margin:0;max-width:100%;overflow-x:hidden}" +
    "#aios-app-root{box-sizing:border-box;max-width:100%;padding:var(--aios-space-4,1rem)}" +
    "#aios-app-root *{max-width:100%;box-sizing:border-box}" +
    "#aios-app-root img{height:auto}" +
    // Wave-2 growth surfaces. Share is the HERO: a prominent, animated (sheen) CTA.
    ".aios-share-cta{display:flex;align-items:center;justify-content:center;gap:.5rem;width:100%;padding:.95rem 1rem;border:0;border-radius:13px;font-size:1.05rem;font-weight:800;letter-spacing:.2px;cursor:pointer;color:#fff;background:linear-gradient(135deg,#7c3aed,#2563eb);box-shadow:0 12px 28px -8px rgba(37,99,235,.6);position:relative;overflow:hidden}" +
    ".aios-share-cta::after{content:'';position:absolute;inset:0;background:linear-gradient(110deg,transparent 32%,rgba(255,255,255,.4) 50%,transparent 68%);transform:translateX(-120%);animation:aios-sheen 2.8s ease-in-out infinite}" +
    ".aios-share-cta:hover{filter:brightness(1.07)}" +
    "@keyframes aios-sheen{0%{transform:translateX(-120%)}55%,100%{transform:translateX(120%)}}" +
    ".aios-share-cta.sm{width:auto;padding:.5rem .85rem;font-size:.82rem;border-radius:10px;box-shadow:0 6px 16px -6px rgba(37,99,235,.5)}" +
    ".aios-share-cta.sm::after{animation-duration:3.4s}" +
    // The polished on-screen full reveal (a designed section, NOT a raw field dump).
    ".aios-reading{display:flex;flex-direction:column;gap:1rem;margin-top:.3rem;padding:1.15rem 1.2rem;border-radius:14px;background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.18)}" +
    ".aios-reading-label{margin:0 0 .3rem;font-size:.66rem;letter-spacing:.12em;text-transform:uppercase;opacity:.6}" +
    ".aios-reading-val{margin:0;font-size:1rem;line-height:1.55;white-space:pre-wrap}" +
    ".aios-reading-chips{display:flex;flex-wrap:wrap;gap:.4rem;margin:.1rem 0 0;padding:0;list-style:none}" +
    ".aios-reading-chip{padding:.28rem .7rem;border-radius:999px;font-size:.85rem;background:rgba(127,127,127,.14);border:1px solid rgba(127,127,127,.24)}" +
    // The tertiary market link + the capture tease.
    ".aios-market-wrap{text-align:center;margin-top:.3rem}" +
    ".aios-market-link{display:inline-block;font-size:.8rem;opacity:.55;text-decoration:none;color:inherit;border-bottom:1px solid transparent}" +
    ".aios-market-link:hover{opacity:.9;border-bottom-color:currentColor}" +
    ".aios-tease{margin:0 0 .55rem;font-size:.98rem;font-weight:600;line-height:1.45}" +
    ".aios-copy-btn{padding:.45rem .9rem;border-radius:9px;border:1px solid rgba(127,127,127,.35);background:rgba(127,127,127,.08);font-size:.85rem;font-weight:600;cursor:pointer;color:inherit}" +
    ".aios-copy-btn:hover{background:rgba(127,127,127,.16)}" +
    // A shareable card + its share control travel together as one unit.
    ".aios-cardunit{display:flex;flex-direction:column;gap:.6rem}" +
    "@media (prefers-reduced-motion: reduce){*{animation:none!important;transition:none!important}}";
  document.head.appendChild(style);
}

function start() {
  const r = root();
  if (!r) return;
  injectResponsiveReset();
  renderQuestions();
}
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
else start();
